name: settleease
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  image_picker: ^1.0.4
  intl_phone_field: ^3.1.0
  
  cloud_firestore: ^4.15.3 # or latest
  # UI icons
  cupertino_icons: ^1.0.8

  # Firebase core and authentication
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.7

  # Google Sign-In for Firebase
  google_sign_in: ^6.2.1

  # State management
  provider: ^6.1.2

  # Optional (for Firestore use in the future)
  # cloud_firestore: ^4.15.8

  flutter_colorpicker: ^1.0.3

  shared_preferences: ^2.2.2 

  path_provider: ^2.0.15
  permission_handler: ^11.0.0
  csv: ^5.0.2

  device_info_plus: ^9.1.0

  
  logger: ^2.0.2

  url_launcher: ^6.2.4
  file_picker: ^8.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/google_icon.png
    - assets/default_avatar.png
    - assets/images/logo.png