// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiY99mgMY9SeqwqLp2MIWDbHvAEPYFAu8',
    appId: '1:701839609799:web:888c8fc114f1f499c353e2',
    messagingSenderId: '701839609799',
    projectId: 'settleease-6e26e',
    authDomain: 'settleease-6e26e.firebaseapp.com',
    storageBucket: 'settleease-6e26e.firebasestorage.app',
    measurementId: 'G-SZKQ03NC6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyI_DBmYvOYLQMuKdmFLu2jiA2gHH-yAQ',
    appId: '1:701839609799:android:0b064bc7c3c8e08bc353e2',
    messagingSenderId: '701839609799',
    projectId: 'settleease-6e26e',
    storageBucket: 'settleease-6e26e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrz1mDi3pQO6JtviWYNwxI8Wi4Ie-Bp8',
    appId: '1:701839609799:ios:34a6afb0edacf40dc353e2',
    messagingSenderId: '701839609799',
    projectId: 'settleease-6e26e',
    storageBucket: 'settleease-6e26e.firebasestorage.app',
    androidClientId: '701839609799-js9koflmftap5erf7rteo84p973duf0m.apps.googleusercontent.com',
    iosClientId: '701839609799-u257brljeilphmtk5jv5gkav2hi761de.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnrz1mDi3pQO6JtviWYNwxI8Wi4Ie-Bp8',
    appId: '1:701839609799:ios:34a6afb0edacf40dc353e2',
    messagingSenderId: '701839609799',
    projectId: 'settleease-6e26e',
    storageBucket: 'settleease-6e26e.firebasestorage.app',
    androidClientId: '701839609799-js9koflmftap5erf7rteo84p973duf0m.apps.googleusercontent.com',
    iosClientId: '701839609799-u257brljeilphmtk5jv5gkav2hi761de.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiY99mgMY9SeqwqLp2MIWDbHvAEPYFAu8',
    appId: '1:701839609799:web:5b75ff0ca2bf9076c353e2',
    messagingSenderId: '701839609799',
    projectId: 'settleease-6e26e',
    authDomain: 'settleease-6e26e.firebaseapp.com',
    storageBucket: 'settleease-6e26e.firebasestorage.app',
    measurementId: 'G-DMVQ2P4BL3',
  );
}
